Update 2fa-cli in light of new phone w/ slightly different `su` binary.

diff --git a/bin/2fa-cli b/bin/2fa-cli
--- a/bin/2fa-cli
+++ b/bin/2fa-cli
@@ -3,7 +3,14 @@
 DB=/tmp/data.db
 
 echo -n "Attempting to connect to phone. You may need to answer a prompt on your phone..." &> /dev/stderr
-sudo adb -d shell "su root -c 'cat /data/data/com.google.android.apps.authenticator2/databases/databases'" > "$DB" 2> /dev/null < /dev/null
+sudo adb -d shell "which su" &> /dev/null < /dev/null
+if [ $? -ne 0 ]; then
+    echo
+    echo "It appears the attached phone is not rooted (could not find a 'su' binary)."
+    echo "This tool will not work if your phone is not rooted. Exiting."
+    exit 1
+fi
+sudo adb -d shell "su -c 'cat /data/data/com.google.android.apps.authenticator2/databases/databases'" > "$DB" 2> /dev/null < /dev/null
 if [ $? -eq 0 ]; then
     echo "success!" &> /dev/stderr
 else
