More colorscheme features
This adds cycle command, which required building a get command, which
required tweaking the set command to store a little more information.
What a fun little adventure this was.

diff --git a/homies/bin/colorscheme b/homies/bin/colorscheme
--- a/homies/bin/colorscheme
+++ b/homies/bin/colorscheme
@@ -40,32 +40,47 @@ function _get_json_colorscheme() {
     local colorscheme=$1
     local file
     file=$(ls ~/.dotfiles/colorschemes/**/"$colorscheme.yml" 2>/dev/null)
-    yq .colors "$file"
+
+    # We are legitimately trying to pass a dollarsign character to yq here.
+    # shellcheck disable=SC2016
+    yq --arg cs "$colorscheme" '.colors + {name: $cs}' "$file"
 }
 
 # Validate command line arguments
 function _print_usage_and_exit() {
     local name
     name=$(basename "$0")
-    echo "## Usage"
-    echo ""
-    echo "    $name set [current|global|PID] [colorscheme]"
-    echo "    $name clear [current|global|PID]"
-    echo "    $name list"
-    echo ""
-    echo "## Examples"
-    echo ""
-    echo "### Set the colorscheme for the current terminal"
-    echo ""
-    echo "    $name current light"
-    echo ""
-    echo "### Reset the colorscheme for the current terminal to the global default"
-    echo ""
-    echo "    $name clear-current"
-    echo ""
-    echo "### Get a list of available colorschemes"
-    echo ""
-    echo "    $name list"
+    cat <<EOF
+## Usage
+
+    $name set [current|global|PID] [colorscheme]
+    $name get [current|global|PID]
+    $name cycle [current|global|PID] [colorscheme]...
+    $name clear [current|global|PID]
+    $name list
+
+## Examples
+
+### Set the colorscheme for the current terminal
+
+    $name set current light
+
+### Get the colorscheme for the current terminal
+
+    $name get current
+
+### Cycle through the given colorschemes
+
+    $name cycle current dark light
+
+### Reset the colorscheme for the current terminal to the global default
+
+    $name clear current
+
+### Get a list of available colorschemes
+
+    $name list
+EOF
     exit 1
 }
 
@@ -74,6 +89,9 @@ function _list() {
         f="$(basename "$f")"
         echo "${f%.yml}"
     done
+}
+function _ls() {
+    _list "$@"
 }
 
 function _set() {
@@ -85,6 +103,77 @@ function _set() {
     local colorscheme=$2
 
     with-alacritty set "$(_get_location "$location")" colors "$(_get_json_colorscheme "$colorscheme")"
+}
+
+function _get() {
+    if [ $# -ne 1 ]; then
+        _print_usage_and_exit
+    fi
+
+    local location=$1
+
+    with-alacritty get "$(_get_location "$location")" | jq --raw-output '.colors.name'
+}
+
+function _index_of_in() {
+    local findme=$1
+    shift
+
+    local found_index=-1
+    local i=0
+    for colorscheme in "$@"; do
+        if [ "$colorscheme" = "$findme" ]; then
+            found_index=$i
+        fi
+        i=$((i + 1))
+    done
+    echo "$found_index"
+}
+
+function _get_ancestor_locations() {
+    local location=$1
+
+    if [ "$location" = "global" ]; then
+        echo "global"
+    else
+        echo "$location global"
+    fi
+}
+
+function _cycle() {
+    if [ $# -eq 0 ]; then
+        _print_usage_and_exit
+    fi
+
+    local location=$1
+    shift
+
+    if [ $# -eq 0 ]; then
+        echo "Must specify at least one colorscheme to cycle through!"
+        exit 1
+    fi
+
+    local curr=""
+    for ancestor_location in $(_get_ancestor_locations "$location"); do
+        curr=$(_get "$ancestor_location")
+        if [ -n "$curr" ] && [ "$curr" != "null" ]; then
+            break
+        fi
+    done
+    if [ -z "$curr" ]; then
+        echo "Could not discover current colorscheme. Giving up!"
+        exit 1
+    fi
+
+    local found_index
+    found_index=$(_index_of_in "$curr" "$@")
+    next_index=$(((found_index + 1) % $#))
+
+    # Offset by 1 to skip past $0
+    next_index=$((1 + next_index))
+
+    local next_colorscheme=${!next_index}
+    _set "$location" "$next_colorscheme"
 }
 
 function _clear() {
